#!/system/bin/sh

# CPU_Optimizer
echo "800000" > /dev/cpuctl/cpu.rt_runtime_us
echo "1000000" > /dev/cpuctl/cpu.rt_period_us
echo "62" > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
echo "700000" > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us
echo "1000000" > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_period_us